Work/stan36/staking controller
zer0-os/zNS-lgc pull request #18
Opened 2021-04-06 17:18 UTC by stan36

cleaned up logic for staking controller with gas efficiency in mind 

added logic for setting metadata, royalty amount and metadata locking

should be done unless additional functionality is decided upon

2021-04-06 20:22 UTC, Remscar requested changes
Looks like a great start.

Beyond the comments I left, I'd recommend avoiding naming things like `ipfsHash` and instead using a name that's more specific to what it is used for. For instance if it's the ipfs hash of the bid which is in ipfs, maybe `bidIpfsLocation` or `bidIpfsHash`.

Variables like `metadata` might also be more clear if it were `metadataUri`.

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +  uint256 private rootDomain;
This isn't used anywhere, please remove it to save on storage gas costs.

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +      bytes32 requestHash,
Is this the hash of the content at the ipfs location (dictated by the ipfsHash)
If so, wouldn't they be the same since the ipfs location is a hash of the content?

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +      emit DomainBidPlaced(
How can this be tied back to the parent domain which the bid is being placed for to create a sub domain.

I could see the subgraph going and fetching the ipfs content, and then reading a `parentId` from there, but i'm unsure as to why `requestHash` is being emitted here.

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +    function approveDomainBid(
I was wrong in my discord message to you about the interfaces;

This function also needs to take the signed message from inside of the ipfs stored file (signature) and mark it as accepted

```
approvedBids[keccak256(abi.encode(ipfsHash))] = signature;
```

or perhaps

```
approvedBids[keccak256(abi.encode(ipfsHash))] = keccak256(signature);
```

(though i'm not sure how much the 2nd will actually save gas)

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +  event DomainBidAccepted(string indexed bidIdentifier);
Rename to `DomainBidApproved` to match the function name

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +  event DomainBidAccepted(string indexed bidIdentifier);
This could be a `bytes32` to save gas

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +      ) external authorizedRecipient(metadata) {
You are using the metadata as if it is the ipfs hash of the bid, which it is not. You're probably going to need to pass in another argument here `ipfsHash`

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +      ) external authorizedRecipient(metadata) {
Also, fulfilling a domain bid should be runnable by anyone, not just the bid placer. The bidder is the one who gets the domain, not the person fulfilling it.

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +        require(bidder == recoveredbidder, 'StakingController: incorrect bid info');
The caller doesn't have to be the bidder (msgSender does not have to be the recoveredBidder)

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +        address recoveredbidder = recover(keccak256(abi.encode(bidAmount, name, parentId, metadata)), signature);
This signature cannot be trusted, it needs to be verified as correct from what is captured in the `approveBid` function.

Otherwise this function is vulnerable and it can currently be attacked:

1. User A makes a bid to create a subdomain of Domain X
2. Domain X owner approves the bid
3. User A passes the same `ipfsHash` (metadata in this function) as they placed the bid with, but sends a different signature + parameters than were in the ipfs stored file
4. User A is now able to create any domain, on any sub domain, at no price

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +      function fulfillDomainBid(
Nothing is preventing this function from being called multiple times with the same bid since a bid is never 'destroyed' or 'expired'

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +    function recover(
After thinking about this more, this can probably just be made a private internal and removed from the interface since it's just a trivial method which other contracts would probably never call

2021-04-06 20:22 UTC, Remscar commented on contracts/StakingController.sol
> +        infinity.transferFrom(bidder, controller, bidAmount);
Using the SafeERC20 wrapper may be helpful here

2021-04-08 16:51 UTC, stan36 commented on contracts/StakingController.sol
> +      bytes32 requestHash,
no, this is the signed message hash for the bid info

2021-04-08 16:55 UTC, stan36 commented on contracts/StakingController.sol
> +      emit DomainBidPlaced(
The request hash is being emitted here for easy retrieval by the parent ID owner so they can use recover to check that the bid info stored in IPFS matches the bid info of the signed message.

2021-04-08 17:05 UTC, stan36 commented on contracts/StakingController.sol
> +  event DomainBidAccepted(string indexed bidIdentifier);
why? DomainBidAccepted is the name I got from the interface file you gave me.

2021-04-08 17:08 UTC, stan36 commented on contracts/StakingController.sol
> +        require(bidder == recoveredbidder, 'StakingController: incorrect bid info');
Why would user A pay the gas for user B to claim their name? I have been trying to limit input params on this function as we will likely need to add additional ones later when we implement the dToken logic.

2021-04-08 17:22 UTC, stan36 commented on contracts/StakingController.sol
> +      function fulfillDomainBid(
can you have multiples of the same domain name?

2021-04-08 17:31 UTC, Remscar commented on contracts/StakingController.sol
> +      bytes32 requestHash,
Could we please rename this to something like `signedBid` then since `requestHash` is vague and doesn't accurately reflect what it is.

2021-04-08 17:31 UTC, Remscar commented on contracts/StakingController.sol
> +      emit DomainBidPlaced(
Okay great, I couldn't tell that `requestHash` was the signed message from the name and type, could we change the name like mentioned in the other comment?

2021-04-08 17:32 UTC, Remscar commented on contracts/StakingController.sol
> +      bytes32 requestHash,
Also I believe that a signed message is longer than 32 bytes, so it's going to need to be a `string` type instead of `bytes32`

2021-04-08 17:34 UTC, stan36 commented on contracts/StakingController.sol
> +        infinity.transferFrom(bidder, controller, bidAmount);
Not sure it is needed as we are only using infinity(and dTokens in the future) all of which are built using standard ERC20 contracts from openZeppelin if I remember correctly. Ill double check with Matt on this and change it if need be.

2021-04-08 17:34 UTC, Remscar commented on contracts/StakingController.sol
> +      function fulfillDomainBid(
You cannot, however this at best would be a bug, but at worse be an attack vector.

One attack for this could be that my bid is approved and then I fulfill it. Later, I release/delete the domain and get my staked tokens back. At any point, I could call this function again and re-fulfill my bid even though i've already done that once. Having a lifetime stake on a domain isn't a part of the design spec.

2021-04-08 17:37 UTC, Remscar commented on contracts/StakingController.sol
> +        require(bidder == recoveredbidder, 'StakingController: incorrect bid info');
There's a couple of reasons I could think of, one of which being an oracle system that automatically fulfills domain bids on behalf of users, but also as an opposite, why not?

We can remove this check and just use `recoveredBidder` instead of `bidder` and the function will operate exactly the same, except now anyone can fulfill domain bids.

2021-04-08 18:23 UTC, Remscar commented on contracts/StakingController.sol
> +  event DomainBidAccepted(string indexed bidIdentifier);
For consistency please, I must've forgotten to update that name when I sent that interface file to you.

2021-04-08 18:24 UTC, Remscar commented on contracts/StakingController.sol
> +        infinity.transferFrom(bidder, controller, bidAmount);
It's not a very big code change to add SafeERC20 and we've already been bit in the past by not using it. We could save ourselves, and possibly someone else some trouble in the future by using it here.

2021-04-15 03:28 UTC, Remscar commented on contracts/StakingController.sol
> +        bytes32 unsignedRequestHash  = approvedBids[keccak256(abi.encode(metadata))];
Domain metadata is different than the bidIPFSHash which is what the key of this mapping is.

2021-04-15 03:29 UTC, Remscar commented on contracts/StakingController.sol
> +      approvedBids[keccak256(abi.encode(bidIPFSHash))] = unsignedRequestHash;
The signature needs to be included here, either hashed and as the key, as the value of the mapping, or hashed and as the value of the mapping.

Without the signature, anyone can act on a bid.

2021-04-15 03:31 UTC, Remscar commented on contracts/StakingController.sol
> +        uint256 id = registrar.registerDomain(parentId, name, controller, parentOwner);
The creator of the domain is the `recoveredBidder` not the `parentOwner` for domains created through the staking controller.

2021-04-15 03:31 UTC, Remscar commented on contracts/StakingController.sol
> +        address recoveredbidder = recover(keccak256(abi.encode(bidAmount, name, parentId, metadata)), signature);
Please rename to `recoveredBidder`

2021-04-15 03:33 UTC, Remscar commented on contracts/StakingController.sol
> +        address recoveredbidder = recover(keccak256(abi.encode(bidAmount, name, parentId, metadata)), signature);
This is still attackable. It is possible to take someone else's bid and fulfill it with a signature that you signed instead, thus making the domain in your name instead of the bidders.

2021-04-15 03:33 UTC, Remscar commented on contracts/StakingController.sol
> +        require(unsignedRequestHash == keccak256(abi.encode(bidAmount, name, parentId, metadata)), 'StakingController: incorrect bid params');
`keccak256(abi.encode(bidAmount, name, parentId, metadata))` should be refactored to a local variable

2021-04-15 03:34 UTC, Remscar commented on contracts/StakingController.sol
> +
Consider adding a helper method `createBid` which would take all the required parameters and return a hash of a bid, ie doing: `keccak256(abi.encode(bidAmount, name, parentId, metadata))`

2021-04-15 03:37 UTC, Remscar commented on package.json
> +    "web3": "^1.2.9"
Remove web3 dependency please

2021-04-15 03:37 UTC, Remscar commented on package.json
> +    "@nomiclabs/ethereumjs-vm": "^4",
Remove this dependency please

2021-04-15 03:37 UTC, Remscar commented on package.json
> +    "@eth-optimism/plugins": "^1.0.0-alpha.3",
Remove this dependency please

2021-04-15 03:37 UTC, Remscar commented on contracts/StakingController.sol
> +contract StakingController is
Hashed and signed messages should implement EIP712 (https://eips.ethereum.org/EIPS/eip-712) for safety

2021-04-15 03:38 UTC, Remscar commented on contracts/mocks/Infinity.sol
> +contract Infinity is Initializable, ERC20Upgradeable {
Rename to `MockToken` please

2021-04-15 03:39 UTC, Remscar commented on test/stakingcontroller.spec.ts
> +      const bidRequestHash = await ethers.utils.keccak256(
Consider refactoring this pattern into a helper

2021-04-15 03:43 UTC, Remscar commented on test/stakingcontroller.spec.ts
> +      describe("FullFills a bid", () => {
This needs failure test cases (scenarios where this will fail) such as:

- Fulfilling a bid that doesn't exist
- Fulfilling a bid with a wrong signature
- Another user signing the bid and trying to fulfill it
- Fulfilling a bid that has already been fulfilled
- Using a different 'metadata' IPFS location than the bid location

2021-04-15 03:44 UTC, Remscar commented on test/stakingcontroller.spec.ts
> +    describe("Accepts a bid", () => {
This needs failure cases tested such as:

- A user approving a bid to a domain they do not own

2021-04-15 03:45 UTC, Remscar commented on test/stakingcontroller.spec.ts
> +    it("emits a DomainBidPlaced event with the correct bid info", async () => {
This needs failure test cases:

- A user placing a bid for a subdomain on a domain that doesn't exist

2021-04-15 03:45 UTC, Remscar commented on contracts/StakingController.sol
> +    require(registrar.domainExists(domain), "Invalid Domain");
Prefix these require messages with `Zer0 Naming Service:`

2021-04-15 03:47 UTC, Remscar commented on contracts/StakingController.sol
> +        infinity.transferFrom(recoveredbidder, controller, bidAmount);
Please use SafeERC20 to make the token transfer.

2021-04-15 20:01 UTC, stan36 commented on contracts/StakingController.sol
> +        bytes32 unsignedRequestHash  = approvedBids[keccak256(abi.encode(metadata))];
I feel this one is worth discussing a bit more as we are gonna hit a "stack too deep" error with the fulfillDomainBid function either by adding another string(and, if not) by adding another address field when we have to add in the dynamicToken logic. To overcome this I figured we could have the metadata for the domain being created contain the bid info for a bid making them the same IPFS hash. This bidInfo feild should be completely ignored by openSea so I dont see a problem with doing things this way.

2021-04-16 01:44 UTC, Remscar commented on contracts/StakingController.sol
> +        return keccak256(abi.encode(bidAmount, name, parentId, bidIPFSHash));
Nitpick: Order the arguments in `abi.encode` to be the same order they appear in the function arugments

2021-04-16 02:46 UTC, Remscar commented on contracts/StakingController.sol
> +        bytes32 unsignedRequestHash  = approvedBids[keccak256(abi.encode(metadata))];
Use a struct for the input then, it will save on # of parameters

2021-04-16 02:47 UTC, Remscar commented on contracts/StakingController.sol
> +        string memory metadata,
I know there was a comment somewhere, but metadata can't be the same as the IPFS hash, but the solution to the `too many args` thing is to use a struct for some of these args

2021-04-16 02:48 UTC, Remscar commented on contracts/StakingController.sol
> +      function createBid(
This should be calling that internal `hash(Bid memory bid)` method you have. That's the hash we want to be using.

2021-04-16 03:01 UTC, Remscar commented on package.json
> +  "dependencies": {
If these are needed, can you move these dependencies into `devDependencies` please

2021-04-16 03:30 UTC, Remscar commented on contracts/interfaces/IStakingController.sol
> +pragma solidity ^0.7.3;
Add `// SPDX-License-Identifier: MIT` to the top of this file please

2021-04-16 03:31 UTC, Remscar commented on contracts/StakingController.sol
> +pragma solidity ^0.7.3;
Add `// SPDX-License-Identifier: MIT` to the top of this file`

2021-04-16 03:31 UTC, Remscar commented on contracts/StakingController.sol
> +contract StakingController is
Disregard please.

2021-04-16 03:44 UTC, Remscar commented
Almost there, just a few small comments and the removal of the EIP712 stuff should put it there for the most part. Just make sure to run the linter and fix any warnings/errors. You can use `yarn fix` to fix most of those automatically.

2021-04-16 03:51 UTC, stan36 commented on contracts/StakingController.sol
> +        bytes32 unsignedRequestHash  = approvedBids[keccak256(abi.encode(metadata))];
hmm, alright. I suppose I can salvage the Bid struct

2021-04-16 03:53 UTC, stan36 commented on package.json
> +  "dependencies": {
I thought I got rid of these so not sure where its coming from. Ill try to hunt that down in the morning

2021-04-16 03:55 UTC, stan36 commented on contracts/interfaces/IStakingController.sol
> +pragma solidity ^0.7.3;
I had it there but removed it because I figured thats where the license field in the json was coming from. I can re-add it but that may work against removing that field from the json.

2021-04-16 03:56 UTC, stan36 commented on package.json
> +  "dependencies": {
yea, I just checked and its still removed in my version.

2021-04-16 16:31 UTC, Remscar approved these changes
lgtm

2021-04-16 16:47 UTC, merged