Work/stan36/staking controller revamp
zer0-os/zNS-lgc pull request #19
Opened 2021-04-21 20:41 UTC by stan36

finished contract rework so that all logic is on-chain  and tests(17 tests with failure cases tested as well as success).

2021-04-21 21:59 UTC, Remscar commented on contracts/StakingController.sol
> +        accepted: false,
`accepted` and `approved` are confusing here since the actions are `place` `approve` `fulfill`

Maybe `accepted` can be changed to `fulfilled`?

2021-04-21 22:04 UTC, Remscar commented on contracts/StakingController.sol
> +        if(!registrar.domainExists(bid.parentId)){
I'm not sure what this code here is doing, or why there is a branch.

It seems that:

If the parent domain doesnt exist you are registering the child domain and then setting the 'domain identifier' of the child domain to the hash of the parent id and the child label.
Else if the parent domain does exist, you are getting the 'domain identifier' and then checking if tokens are being held.

When would this be called where the parent domain doesn't exist? And if the parent domain doesn't exist then this call should fail.

2021-04-21 22:05 UTC, Remscar commented on contracts/StakingController.sol
> +           domainId = keccak256(abi.encode(bid.parentId, bid.name));
I think you're trying to get the domain Id of the child domain here, but this isn't how you do it.

Use this snippet:
```
uint256 labelHash = uint256(keccak256(bytes(name)));
uint256 domainId = uint256(keccak256(abi.encodePacked(parentId, labelHash)));
```

2021-04-21 22:06 UTC, Remscar commented on contracts/StakingController.sol
> +        bid.approved = true;
This is deceptive, maybe create a different flag in the bid structure and call it `valid` and if the bid has been fulfilled or withdrawn, `valid` is set to false.

2021-04-21 22:06 UTC, Remscar commented on contracts/StakingController.sol
> +        uint256 tokenId
rename `tokenId` to `domainId`

2021-04-21 22:08 UTC, Remscar commented on contracts/StakingController.sol
> +        registrar.transferFrom(_msgSender(), controller, tokenId);
This isn't a safe way of relinquishing ownership because it just gives it back to the controller.

The domain NFT should be burned here, which means a call to the registrar, however there is no burn method, so that would need to be added.

2021-04-21 22:08 UTC, Remscar commented on contracts/StakingController.sol
> +        infinity.safeTransfer(bid.bidder, bid.bidAmount);
`safeTransfer` needs to be done last here

2021-04-21 22:08 UTC, Remscar commented on contracts/StakingController.sol
> +        infinity.safeTransferFrom(bid.bidder, controller, bid.bidAmount);
`safeTransfer` needs to be done last here

2021-04-21 22:09 UTC, Remscar commented on contracts/StakingController.sol
> +          registrar.unlockDomainMetadata(tokenId);
This call will always fail, if the domain metadata is locked, it will have been locked by the owner and the controller doesn't have authorization to unlock the metadata through this call.

2021-04-21 22:10 UTC, Remscar requested changes
Left some preliminary comments. Please also change the concept of `bid` to `offer` or `request`.

There has been a great deal of confusion about `bidding` which implies this is an auction when it's more of a `request` or `offer` system.

2021-04-21 22:23 UTC, stan36 commented on contracts/StakingController.sol
> +        if(!registrar.domainExists(bid.parentId)){
yea, this was supposed to check if the domain name being created's ID exists already but I kinda masked the problem with the way I wrote the test, good catch

2021-04-21 22:26 UTC, stan36 commented on contracts/StakingController.sol
> +           domainId = keccak256(abi.encode(bid.parentId, bid.name));
This actually helps a lot and means I can get rid of one of the mappings I made to fill a gap in knowledge here, thanks

2021-04-21 22:31 UTC, stan36 commented on contracts/StakingController.sol
> +        registrar.transferFrom(_msgSender(), controller, tokenId);
Thats kinda why I did it this way. Why wouldnt it be safe to just allow the controller to hold a relinquished domain until someone else stakes it?

2021-04-21 22:51 UTC, stan36 commented on contracts/StakingController.sol
> +        registrar.transferFrom(_msgSender(), controller, tokenId);
I guess I am just going to remove this functionality for now seeing as we cannot overcome the metadata locking problem easily

2021-04-21 23:06 UTC, Remscar commented on contracts/StakingController.sol
> +  mapping(bytes32 => uint256) public domainIdentifier;
Remove this please

2021-04-21 23:06 UTC, Remscar commented on contracts/StakingController.sol
> +  mapping(uint256 => bool) public tokensHeld;
Remove this please (unused)

2021-04-21 23:07 UTC, Remscar commented on contracts/StakingController.sol
> +  mapping(uint256 => Request) public acceptedRequests;
Remove this please (set, but never read from)

2021-04-21 23:07 UTC, Remscar commented on contracts/StakingController.sol
> +        require(request.valid == false, "ZNS: request not valid");
Request should be valid to be fulfilled

2021-04-21 23:08 UTC, Remscar commented on contracts/StakingController.sol
> +        valid: false
valid should be true to start

2021-04-21 23:09 UTC, Remscar commented on contracts/StakingController.sol
> +      uint256 _parentId,
Please remove the `_` in the argument names so they are consistent with the rest of the file/codebase. Only use the `_` if it is needed.

2021-04-21 23:10 UTC, Remscar commented on contracts/StakingController.sol
> +        request.fulfilled = true;
Also set `valid` to false

2021-04-21 23:12 UTC, Remscar commented on contracts/StakingController.sol
> +        require(request.accepted == false, "ZNS: request already accepted");
This should be checking whether or not the request is valid, and only allow valid requests (`request.valid == true`)

2021-04-21 23:12 UTC, Remscar commented on contracts/StakingController.sol
> +        request.valid = true;
This should be setting valid to false

2021-04-21 23:13 UTC, Remscar commented on contracts/StakingController.sol
> +        require(request.fulfilled == false, "ZNS: already fulfilled");
If you do my comment that is later in this file (set valid to false when fulfilled) then you can remove this

2021-04-21 23:14 UTC, Remscar requested changes
Almost there

2021-04-21 23:16 UTC, Remscar commented on contracts/interfaces/IStakingController.sol
> +  function withdrawRequest(uint256 bidIdentifier) external;
This should be removed

2021-04-21 23:16 UTC, Remscar commented on contracts/StakingController.sol
>    ERC721HolderUpgradeable
Make sure to have this implement `IStakingController` (use as a parent)

2021-04-21 23:44 UTC, stan36 commented on contracts/interfaces/IStakingController.sol
> +  function withdrawRequest(uint256 bidIdentifier) external;
Why would I remove this? Every other function has an implementation in the interface so I don't understand why I would remove this one.

2021-04-21 23:49 UTC, Remscar commented on contracts/interfaces/IStakingController.sol
> +  function withdrawRequest(uint256 bidIdentifier) external;
Please disregard

2021-04-21 23:59 UTC, Remscar commented on contracts/StakingController.sol
> +    uint256 requestAmount;
Consider renaming this to `offeredAmount` since it might be confusing that this is a request, but they are not requesting an amount, they are requesting a name

2021-04-21 23:59 UTC, Remscar commented on contracts/StakingController.sol
> +    string name;
Consider renaming to `requestedName` since they are requesting this name with this request

2021-04-22 00:00 UTC, Remscar commented on contracts/StakingController.sol
> +        require(request.accepted == false, "ZNS: request already accepted");
Still not resolved

2021-04-22 00:05 UTC, stan36 commented on contracts/StakingController.sol
> +        require(request.fulfilled == false, "ZNS: already fulfilled");
it wont let me resolve this for some dumb reason

2021-04-22 01:03 UTC, Remscar commented on contracts/StakingController.sol
> +      require(request.offeredAmount != 0, "ZNS: Request doesnt exist");
A safer way to check if the request exists is to check `request.valid` instead. This is really just checking if the offered amount isn't zero, but maybe they want to only offer zero tokens

2021-04-22 19:04 UTC, Remscar approved these changes
lgtm

2021-04-22 19:19 UTC, merged