Feature/opensea operator filter
zer0-os/zNS-lgc pull request #61
Opened 2022-11-17 18:11 UTC by beardhero

Incorporates opensea operator filter functionality with the Registrar

2022-11-18 17:01 UTC, JamesEarle approved these changes

2022-11-18 18:12 UTC, JamesEarle requested changes
Some things pending

2022-11-18 20:24 UTC, JamesEarle reviewed
Thanks for the tests. There are a few things I didn't think about on my earlier pass through, so please address each. Also, I mentioned I did a small test upgrade script myself and it seemed okay but please write your own to make sure it upgrades the existing registrar and proxy beacon to make sure all the upgrade comments I made are safe.

2022-11-18 20:24 UTC, JamesEarle commented on contracts/opensea/DefaultOperatorFilterer.sol
> +pragma solidity ^0.8.13;
This file looks unused because you use the `OperatorFilterer` contract direct just calling to `initializeFilter` with the same address in the Registrar. Please remove unused code.

2022-11-18 20:24 UTC, JamesEarle commented on contracts/opensea/OwnedRegistrant.sol
> +pragma solidity ^0.8.13;
This file is unused as well, and also is using a constructor and wouldn't support upgradability modifications you made to the others. Please remove.

2022-11-18 20:24 UTC, JamesEarle commented on contracts/oz/access/Ownable2Step.sol
> +pragma solidity ^0.8.0;
If this file is only being used by the above, unused, `OwnedRegistrant` please also remove this.

2022-11-18 20:24 UTC, JamesEarle commented on contracts/registrar/Registrar.sol
> -  uint8 private test; // ignore
When I tested using my own deployment script these changes didn't throw errors but alterations to storage layouts like this and the above addition of the `contract Registrar is ..., OperatorFilter` would be an unsafe upgrade. Please write your own upgrade script to confirm that these changes are upgrade safe.

2022-11-18 20:24 UTC, JamesEarle commented on contracts/registrar/Registrar.sol
> +    return _exists(id);
Even with simpler functions like this code readability and debug ability is improved when we first assign to a variable and return it. Considering this change is already made by the optimizer when we deploy the contract I'd recommend you revert this and the several other functions below it.

2022-11-18 20:24 UTC, JamesEarle commented on contracts/registrar/Registrar.sol
> +  /**`
Remove backtick

2022-11-18 20:24 UTC, JamesEarle commented on package.json
> +    "@nomiclabs/hardhat-ethers": "^2.2.1",
Please remove `^` here and elsewhere

2022-11-18 20:24 UTC, JamesEarle commented on hardhat.config.ts
> +//require('@eth-optimism/smock/build/src/plugins/hardhat-storagelayout')
Remove unused code

2022-11-18 20:24 UTC, JamesEarle commented on hardhat.config.ts
> +        url: "https://eth-mainnet.alchemyapi.io/v2/-nhhIZg46QlTmzPozXF07vyxpK5BGukx",
Did changing from `rinkeby` to mainnet but still using `infura` not work? I'd avoid changing providers

2022-11-18 20:24 UTC, JamesEarle commented on package.json
> +    "forge-std": "^1.1.2"
Seems like neither if these are used (the smock package is commented out in the hardhat config to boot) please remove unused code

2022-11-18 20:24 UTC, JamesEarle commented on contracts/registrar/Registrar.sol
> +    initializeFilter(address(0x3cc6CddA760b79bAfa08dF41ECFA224f810dCeB6), true);
I'm realizing this won't work for anything except this registrar and registrar's going forwards in time, but we have several existing registrars that will also need this update and won't receive it via this upgrade. Please add functionality to set this, likely through the hub as it points to the already existing registrars in question.

2022-11-21 09:18 UTC, beardhero commented on hardhat.config.ts
> +//require('@eth-optimism/smock/build/src/plugins/hardhat-storagelayout')
removed

2022-11-21 09:18 UTC, beardhero commented on contracts/registrar/Registrar.sol
> +  /**`
removed

2022-11-21 09:18 UTC, beardhero commented on contracts/registrar/Registrar.sol
> +    return _exists(id);
This is not handled by the compiler like you'd normally expect.
This change results in reduced restricted stack usage.

2022-11-21 09:19 UTC, beardhero commented on contracts/registrar/Registrar.sol
> +    initializeFilter(address(0x3cc6CddA760b79bAfa08dF41ECFA224f810dCeB6), true);
Optimization. Further optimization must be decided on to change.

2022-11-21 09:19 UTC, beardhero commented on contracts/registrar/Registrar.sol
> -  uint8 private test; // ignore
Re-added unused variables.
Upgrade tests are out-of-scope.

2022-11-21 09:19 UTC, beardhero commented on contracts/oz/access/Ownable2Step.sol
> +pragma solidity ^0.8.0;
removed

2022-11-21 09:19 UTC, beardhero commented on contracts/opensea/OwnedRegistrant.sol
> +pragma solidity ^0.8.13;
removed

2022-11-21 09:19 UTC, beardhero commented on contracts/opensea/DefaultOperatorFilterer.sol
> +pragma solidity ^0.8.13;
removed

2022-11-21 09:19 UTC, beardhero commented on package.json
> +    "forge-std": "^1.1.2"
> removed

2022-11-21 09:19 UTC, beardhero commented on package.json
> +    "@nomiclabs/hardhat-ethers": "^2.2.1",
removed

2022-11-21 09:19 UTC, beardhero commented on hardhat.config.ts
> +        url: "https://eth-mainnet.alchemyapi.io/v2/-nhhIZg46QlTmzPozXF07vyxpK5BGukx",
Copied mainnet provider below.

2022-12-13 19:20 UTC, closed without merging